version: '3'
services:
  backend:
    image: "${CI_PIPELINE_ID}:${CI_BUILD_REF_NAME}"
    restart: always
    env_file:
      - prod.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  postgres:
    
