# Generated by Django 2.0.3 on 2018-11-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='category',
            field=models.IntegerField(choices=[(-1, 'Low Power \n < 10 W/kg'), (10, 'Intermediate Power\n 10 < x < 20 W/kg'), (20, 'High Power\n 20 < x < 35 W/kg'), (35, 'Enormous Power\n 35 < x < 55 W/kg'), (55, 'Maximum Power\n  55 W/kg <')], default=-1, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='powercategroy',
            name='category',
            field=models.IntegerField(choices=[(-1, 'Low Power \n < 10 W/kg'), (10, 'Intermediate Power\n 10 < x < 20 W/kg'), (20, 'High Power\n 20 < x < 35 W/kg'), (35, 'Enormous Power\n 35 < x < 55 W/kg'), (55, 'Maximum Power\n  55 W/kg <')], verbose_name='category'),
        ),
    ]
