# Generated by Django 2.0.3 on 2018-11-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Member', verbose_name='member'),
        ),
        migrations.AddField(
            model_name='session',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='data',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='trackers.Session', verbose_name='session'),
        ),
    ]
