# Generated by Django 2.0.3 on 2018-11-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_user'),
        ('files', '0003_auto_20181127_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Member', verbose_name='member'),
            preserve_default=False,
        ),
    ]
