# Generated by Django 2.0.3 on 2018-11-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0005_session_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='team.Member', verbose_name='member'),
        ),
    ]
