# Generated by Django 2.0.3 on 2018-12-04 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0007_auto_20181203_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='filename'),
            preserve_default=False,
        ),
    ]
