# Generated by Django 2.0.3 on 2018-11-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20181128_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.FloatField(default=1.6, verbose_name='height'),
            preserve_default=False,
        ),
    ]
